### PR TITLE
supports half bathrooms

### LINKED ISSUE #497: Support for Half Bathrooms in Create Listing
# Background

Currently, we can only have whole number of bathrooms, which doesn't specify that a property has a half bathroom. 

image

# Task

* Allow for whole number or 0.5 increments in the box specifying number of bathrooms

# Done When

### PR DESCRIPTION
**Pull request by syd-tan**
# Support half bathrooms and bedrooms when creating a listing

Closes #497 

# Summary of change

- Can now create a listing and submit a form with half bedrooms and bathrooms.
- Also added red asterisks to required fields.

# Testing/Verification

When creating a listing:
 - Text fields for bedrooms and bathrooms should support whole numbers and decimals ending in 0.5 (but no other decimals).
 - Text field for maximum people should still only support whole numbers.
 - Should see red asterisks next to required fields (please double check if the required fields are correct!)

### CODE REVIEW

**Review by aidenszeto — CHANGES_REQUESTED** [review]
Looks great! I think adding the red asterisks was a nice touch. A few tiny comments:

1. I believe "Emaill to Transfer to" has the `required` tag but is not actually validated on form submission so listings can be created without it being filled (we can probably remove the `required` tag as well)
image

2. State and Country are validated when submitting as well, so we should add both the `required` tag and the red asterisk to the two of them. We must have forgotten to mark them as required before.

**Comment by nishantbalaji** [comment]
> Looks great! I think adding the red asterisks was a nice touch. A few tiny comments:

Yeah, great touch with this, I'll link #498 to it as well because I think this addresses the concerns I brought up with that issue!

**Review by nishantbalaji — APPROVED** [review]

**Comment by syd-tan** [comment]
@aidenszeto Updated the required fields and tags!

**Review by aidenszeto — APPROVED** [review]
LGTM!

**Pull request merged**
