### PR TITLE
Updated listings containers to hide draft listings

### LINKED ISSUE #542: Remove Draft Listings
# Background
The drafted listings shouldn't appear on the listing containers

# Task
- Remove "drafted" listings from the listings containers
- Show the drafted listing if they are the host of the listing.

# Done When
- The "drafted" listing should be removed from featured listings.

### PR DESCRIPTION
**Pull request by aidenszeto**
# Relevant issue

Closes #542

# Summary of change

 - Updated public listing containers to hide draft or expired (inactive) listings

# Testing/Verification

image
 - Listings formatted like the third listing in the image above should be hidden in all public listing containers
 - Draft listings should still be visible in MyAccount when a host has "Show Drafts" toggled on in MyListings

### CODE REVIEW

**Review by nishantbalaji — APPROVED** [review]
lgtm

**Comment by syd-tan** [comment]
My draft still shows up in featured and the recently posted listings for some reason. 

Screen Shot 2021-09-06 at 8 08 44 PM
Screen Shot 2021-09-06 at 8 08 49 PM

**Comment by aidenszeto** [comment]
> My draft still shows up in featured and the recently posted listings for some reason.
> 
> Screen Shot 2021-09-06 at 8 08 44 PM
> 
> Screen Shot 2021-09-06 at 8 08 49 PM

Not sure if this may be related but it looks like there are 2 identical listings called "Cozy 2 Bed 2 Bath near Sac Town Center" in the dev database. One is active meaning it should be displayed in the featured section and the other is inactive.

image

Could this be causing the behavior you found?

**Comment by syd-tan** [comment]
@aidenszeto  Oh i do remember trying to make the same listing twice so that might be the case - but this means that there's an error with the listings tab in MyProfile since i only saw the expired one

**Comment by aidenszeto** [comment]
@syd-tan thanks for the catch. It looks like we were still hiding expired listings even though all expired listings should already be automatically be converted to drafts (from the ticket you worked on a while back). That behavior was legacy and the most recent commit should have the fixes. I left in the code for filtering expired listings in case we want to mess with that in the future tho.

image
Also I manually changed both of these to drafts since they were both expired. I'm guessing we had created one of them prior to the automatic nodecron draft conversion which was why it was left as active.

**Review by syd-tan — APPROVED** [review]
I see both drafts now! LGTM

**Pull request merged**
