### PR TITLE
Updated signup to also log user in

### LINKED ISSUE #496: Signing up should log you in
# Background

Currently, when you sign up for an account, it redirects you back to the login page. This step should be eliminated to simplify the user workflow

# Task

* Change flow so signing up for an account logs you into the site, rather than redirecting to the login page

# Done When

* Signing up for an account automatically logs you in.

### PR DESCRIPTION
**Pull request by aidenszeto**
# Relevant issue

Closes #496 

# Summary of change

 - Added automatic login after user signs up

# Testing/Verification

 - Newly signed-up account should automatically log in instead of redirecting to login page

### CODE REVIEW

**Review by nishantbalaji — CHANGES_REQUESTED** [review]
Broke when I clicked sign-up

image
image
image

**Comment by aidenszeto** [comment]
> Broke when I clicked sign-up
> 
> image
> image
> image
> 
> 

Did you try using the Google signup? This PR is for signing up without Google

**Comment by syd-tan** [comment]
It took me back to the main page after I signed up without being logged in.

**Comment by nishantbalaji** [comment]
> > Broke when I clicked sign-up
> > image
> > image
> > image
> 
> Did you try using the Google signup? This PR is for signing up without Google

@aidenszeto nope, just normal sign up

**Comment by aidenszeto** [comment]
> It took me back to the main page after I signed up without being logged in.

Thanks for the catch, should be fixed with new commit

**Comment by aidenszeto** [comment]
> > > Broke when I clicked sign-up
> > > image
> > > image
> > > image
> > 
> > 
> > Did you try using the Google signup? This PR is for signing up without Google
> 
> @aidenszeto nope, just normal sign up

Are you on the right branch? The error from console shows something happening on line 47 and the params access on line 47 is only on `master`

**Comment by nishantbalaji** [comment]
@aidenszeto 
Odd, I'll delete and reclone the branch

**Comment by nishantbalaji** [comment]
image
on the right branch and i see this so idrk

**Comment by aidenszeto** [comment]
@nishantbalaji looks like you were right about the error, new backend changes should fix the issue you found though

**Review by nishantbalaji — APPROVED** [review]
well, it works but i have no idea why so i think the pr is good if it works for syd

**Review by syd-tan — APPROVED** [review]
Worked for me!

**Pull request merged**
